export const resturants = [
  {
    name: "Aarhus Burger",
    distance: "2,8 km",
    rating: "4,6",
    tasteRating: "5.0",
    textureRating: "4.4",
    visualRating: "4.6",
    openingHours: "10:00 - 00:00",
    address: "Aarhusvej 15",
  },
  {
    name: "Burger Boom",
    distance: "1,9 km",
    rating: "4,8",
    tasteRating: "5.0",
    textureRating: "4.4",
    visualRating: "4.6",
    openingHours: "10:00 - 21:00",
    address: "Aarhusvej 15",
  },
  {
    name: "McDonalds",
    distance: "2,1 km",
    rating: "4,2",
    tasteRating: "5.0",
    textureRating: "4.4",
    visualRating: "4.6",
    openingHours: "07:00 - 01:00",
    address: "Aarhusvej 15",
  },
  {
    name: "BurgerKing",
    distance: "0.6 km",
    rating: "4,1",
    tasteRating: "5.0",
    textureRating: "4.4",
    visualRating: "4.6",
    openingHours: "10:00 - 22:00",
    address: "Aarhusvej 15",
  },
  {
    name: "Byens Burger",
    distance: "1,2 km",
    rating: "3,8",
    tasteRating: "5.0",
    textureRating: "4.4",
    visualRating: "4.6",
    openingHours: "10:00 - 22:00",
    address: "Aarhusvej 15",
  },
];
